language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer selfupdate
  - composer install
  - composer require "jackalope/jackalope" "dev-node_validator as dev-master"

script: phpunit

matrix:
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#jackalope"
