language: php

php:
  - 5.5

before_script:
  - composer selfupdate
  - composer install

script: phpunit

matrix:
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#jackalope"
